name: Docker Deploy to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH and Deploy with Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p ~/kray-app && cd ~/kray-app
            if [ ! -d ".git" ]; then
              git clone https://x-access-token:${{ secrets.EC2_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git .
            else
            git remote set-url origin https://x-access-token:${{ secrets.EC2_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
              git pull origin main
            fi
            docker-compose down --remove-orphans || true
            sudo fuser -k 80/tcp
            docker-compose up -d --build
            docker image prune -f

# Use classic token github
