name: Docker Deploy to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH and Deploy with Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p ~/kray-app && cd ~/kray-app
            if [ ! -d ".git" ]; then
              git clone https://x-access-token:${{ secrets.EC2_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git .
              git remote set-url origin https://x-access-token:${{ secrets.EC2_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            else
              git pull origin main
            fi
            docker-compose down --remove-orphans || true
            sudo -n fuser -k 3000/tcp
            docker system prune -a --volumes -f
            docker-compose up -d --build
            docker image prune -f

# Use classic token github
# test
# need to the app run on port 3000, and use nginx redirect to port

##Config ssl
# Tạo thư mục lưu trữ file xác thực trên máy host
# sudo mkdir -p /var/www/html/.well-known/pki-validation/
# Tạo file với nội dung và tên file chính xác từ ảnh của bạn
# sudo bash -c 'printf "FC1AB4919E13A93C27DD8F6F55540462.5DB9A51EEC64F4BF850FD0D506CDF726\nsectigo.com\nnjwWCcFT" > /var/www/html/.well-known/pki-validation/D36B92984314CFDB40CC52AD372CEB53.txt'
# Cấp quyền đọc cho Nginx
# sudo chmod -R 755 /var/www/html/.well-known
